import type { WeekInfo } from "./types";

// Week-by-week pregnancy reference (gestational weeks): size comparison +
// approx dimensions + a development note. Lengths are typical crown-to-rump
// (early) / crown-to-heel (later) figures; treat as friendly estimates.
export const WEEK_DATA: Record<number, WeekInfo> = {
  4:  { emoji: "🌱", fruit: "Poppy seed",     size: "2 mm",            note: "The embryo is implanting. The neural tube, which becomes the brain and spine, is forming." },
  5:  { emoji: "🌾", fruit: "Sesame seed",    size: "3 mm",            note: "The heart begins to form and may start a faint, fluttering beat this week." },
  6:  { emoji: "🫛", fruit: "Sweet pea",      size: "5 mm",            note: "Tiny buds that will become arms and legs appear. The heartbeat is often detectable now." },
  7:  { emoji: "🫐", fruit: "Blueberry",      size: "1 cm",            note: "The brain is growing fast and hands and feet are emerging as little paddles." },
  8:  { emoji: "🫘", fruit: "Kidney bean",    size: "1.6 cm",          note: "Fingers and toes are forming and the baby is starting to make tiny movements." },
  9:  { emoji: "🍒", fruit: "Cherry",         size: "2.3 cm",          note: "Essential organs are in place. The baby now has the basic shape it will keep growing into." },
  10: { emoji: "🍓", fruit: "Strawberry",     size: "3.1 cm",          note: "Vital organs are working. Tiny nails are starting to form on fingers and toes." },
  11: { emoji: "🍋", fruit: "Lime",           size: "4.1 cm, 7 g",     note: "The baby can open and close its fists and is moving a lot, though you can't feel it yet." },
  12: { emoji: "🫒", fruit: "Plum",           size: "5.4 cm, 14 g",    note: "Reflexes are developing. The baby may start to make sucking movements." },
  13: { emoji: "🍋", fruit: "Lemon",          size: "7.4 cm, 23 g",    note: "Vocal cords are forming and unique fingerprints are appearing on the fingertips." },
  14: { emoji: "🍑", fruit: "Peach",          size: "8.7 cm, 43 g",    note: "The baby can squint, frown, and grimace. The body is now growing faster than the head." },
  15: { emoji: "🍎", fruit: "Apple",          size: "10 cm, 70 g",     note: "Bones and the skeleton are hardening. The baby can sense light through closed eyelids." },
  16: { emoji: "🥑", fruit: "Avocado",        size: "11.6 cm, 100 g",  note: "Eyes and ears are nearly in place and the baby can make small, coordinated movements." },
  17: { emoji: "🍐", fruit: "Pear",           size: "13 cm, 140 g",    note: "A protective coating called vernix forms on the skin. Fat stores begin to develop." },
  18: { emoji: "🫑", fruit: "Bell pepper",    size: "14.2 cm, 190 g",  note: "The baby can yawn and hiccup. You may begin to feel the first flutters of movement." },
  19: { emoji: "🥭", fruit: "Mango",          size: "15.3 cm, 240 g",  note: "Sensory development is booming - the brain is mapping touch, taste, sight, and hearing." },
  20: { emoji: "🍌", fruit: "Banana",         size: "16.4 cm, 300 g",  note: "Halfway there. The baby is swallowing and producing meconium, its first stool." },
  21: { emoji: "🥕", fruit: "Carrot",         size: "26.7 cm, 360 g",  note: "Movements are stronger and more frequent. The baby can taste flavors from your meals." },
  22: { emoji: "🍈", fruit: "Papaya",         size: "27.8 cm, 430 g",  note: "Lips, eyelids, and eyebrows are more distinct. The baby looks like a tiny newborn now." },
  23: { emoji: "🍈", fruit: "Grapefruit",     size: "28.9 cm, 500 g",  note: "The baby can hear your voice and may startle at loud sounds. Skin is still wrinkled." },
  24: { emoji: "🌽", fruit: "Ear of corn",    size: "30 cm, 600 g",    note: "A milestone of viability. The lungs are developing branches and producing surfactant." },
  25: { emoji: "🥬", fruit: "Cauliflower",    size: "34.6 cm, 660 g",  note: "The baby is filling out and responding to your voice and touch with movement." },
  26: { emoji: "🥬", fruit: "Lettuce",        size: "35.6 cm, 760 g",  note: "Eyes begin to open. The baby is taking practice breaths of amniotic fluid." },
  27: { emoji: "🥦", fruit: "Broccoli",       size: "36.6 cm, 875 g",  note: "Brain activity is increasing and the baby now has regular sleep and wake cycles." },
  28: { emoji: "🍆", fruit: "Eggplant",       size: "37.6 cm, 1 kg",   note: "Third trimester begins. The baby can blink and may be dreaming during REM sleep." },
  29: { emoji: "🎃", fruit: "Butternut squash", size: "38.6 cm, 1.2 kg", note: "Muscles and lungs are maturing and the head is growing to make room for the brain." },
  30: { emoji: "🥬", fruit: "Cabbage",        size: "39.9 cm, 1.3 kg", note: "The baby's brain is developing fast and it can now regulate its own body temperature better." },
  31: { emoji: "🥥", fruit: "Coconut",        size: "41.1 cm, 1.5 kg", note: "All five senses are working. The baby is putting on weight steadily now." },
  32: { emoji: "🎃", fruit: "Squash",         size: "42.4 cm, 1.7 kg", note: "Practice breathing continues and the baby may be settling into a head-down position." },
  33: { emoji: "🍍", fruit: "Pineapple",      size: "43.7 cm, 1.9 kg", note: "Bones are hardening, though the skull stays soft and flexible for delivery." },
  34: { emoji: "🍈", fruit: "Cantaloupe",     size: "45 cm, 2.1 kg",   note: "The central nervous system and lungs are maturing. Vernix is getting thicker." },
  35: { emoji: "🍈", fruit: "Honeydew",       size: "46.2 cm, 2.4 kg", note: "The baby is rapidly gaining weight. Most internal development is now complete." },
  36: { emoji: "🥬", fruit: "Romaine",        size: "47.4 cm, 2.6 kg", note: "The baby is likely head-down and getting cozy. It's gaining about an ounce a day." },
  37: { emoji: "🥬", fruit: "Swiss chard",    size: "48.6 cm, 2.9 kg", note: "Early term. The baby is practicing breathing, sucking, and gripping in preparation." },
  38: { emoji: "🧅", fruit: "Leek",           size: "49.8 cm, 3.1 kg", note: "Organs are ready for life outside. The baby is shedding most of its downy hair." },
  39: { emoji: "🍉", fruit: "Mini watermelon", size: "50.7 cm, 3.3 kg", note: "Full term. The baby's brain and lungs continue maturing right up to birth." },
  40: { emoji: "🍉", fruit: "Watermelon",     size: "51.2 cm, 3.5 kg", note: "Due date. The baby is ready to meet you - though only about 5% arrive exactly on time." },
};
